[tox]
envlist = py3{9,10,11,12,13}-{tests,types}

[testenv:py3{9,10,11,12,13}-tests]
deps =
    pytest
    pytest-xdist
    pytest-monkeytype
commands =
    pytest {posargs}

[testenv:py3{9,10,11,12,13}-types]
deps =
    mypy
    types-requests
    types-six
    types-PyYAML
    keyring
    json-e
    packaging
commands =
    mypy {posargs} -p webkitcorepy
skipsdist=True




[pytest]
python_files=*_unittest.py *_integrationtest.py
xfail_strict=true
addopts = -rfEX --strict-markers
